/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html",
    "./js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed-variant": "#5f4100",
        "inverse-primary": "#b6c4ff",
        "on-surface": "#151c22",
        "on-tertiary-fixed-variant": "#2d4384",
        "on-surface-variant": "#3b4661",
        "tertiary-fixed-dim": "#b5c4ff",
        "secondary-container": "#feb71a",
        "background": "#f6f9ff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "outline": "#747684",
        "surface-bright": "#f6f9ff",
        "surface-dim": "#d4dbe3",
        "surface-container-highest": "#dce3eb",
        "surface-variant": "#dce3eb",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#ebf1fa",
        "on-primary-fixed": "#001550",
        "surface": "#f6f9ff",
        "on-tertiary-fixed": "#00164d",
        "surface-tint": "#3456c2",
        "outline-variant": "#c4c5d5",
        "error": "#ba1a1a",
        "on-primary-container": "#8fa6ff",
        "secondary-fixed-dim": "#ffba30",
        "on-secondary-fixed": "#271900",
        "tertiary": "#072465",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#93a8f0",
        "secondary-fixed": "#ffdeab",
        "on-primary-fixed-variant": "#133ca9",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#dbe1ff",
        "secondary": "#1D3A83",
        "primary-fixed-dim": "#b6c4ff",
        "tertiary-container": "#253b7c",
        "surface-container": "#e8eff7",
        "inverse-surface": "#2a3137",
        "on-background": "#151c22",
        "on-secondary-container": "#6c4a00",
        "on-secondary": "#ffffff",
        "primary-container": "#0033a1",
        "surface-container-high": "#e2e9f1",
        "surface-container-low": "#eef4fc",
        "on-error": "#ffffff",
        "primary-fixed": "#dce1ff",
        "primary": "#00216f"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
